const NGA_SMILE_BASE_URL = "https://img4.nga.178.com/ngabbs/post/smile/";

const defaultSmiles: Record<string, string> = {
  "1": "smile.gif",
  "2": "mrgreen.gif",
  "3": "question.gif",
  "4": "wink.gif",
  "5": "redface.gif",
  "6": "sad.gif",
  "7": "cool.gif",
  "8": "crazy.gif",
  "24": "04.gif",
  "25": "05.gif",
  "26": "06.gif",
  "27": "07.gif",
  "28": "08.gif",
  "29": "09.gif",
  "30": "10.gif",
  "32": "12.gif",
  "33": "13.gif",
  "34": "14.gif",
  "35": "15.gif",
  "36": "16.gif",
  "37": "17.gif",
  "38": "18.gif",
  "39": "19.gif",
  "40": "20.gif",
  "41": "21.gif",
  "42": "22.gif",
  "43": "23.gif",
};

const acSmiles: Record<string, string> = {
  blink: "ac0.png",
  goodjob: "ac1.png",
  "上": "ac2.png",
  "中枪": "ac3.png",
  "偷笑": "ac4.png",
  "冷": "ac5.png",
  "凌乱": "ac6.png",
  "反对": "ac7.png",
  "吓": "ac8.png",
  "吻": "ac9.png",
  "呆": "ac10.png",
  "咦": "ac11.png",
  "哦": "ac12.png",
  "哭": "ac13.png",
  "哭1": "ac14.png",
  "哭笑": "ac15.png",
  "哼": "ac16.png",
  "喘": "ac17.png",
  "喷": "ac18.png",
  "嘲笑": "ac19.png",
  "嘲笑1": "ac20.png",
  "囧": "ac21.png",
  "委屈": "ac22.png",
  "心": "ac23.png",
  "忧伤": "ac24.png",
  "怒": "ac25.png",
  "怕": "ac26.png",
  "惊": "ac27.png",
  "愁": "ac28.png",
  "抓狂": "ac29.png",
  "抠鼻": "ac30.png",
  "擦汗": "ac31.png",
  "无语": "ac32.png",
  "晕": "ac33.png",
  "汗": "ac34.png",
  "瞎": "ac35.png",
  "羞": "ac36.png",
  "羡慕": "ac37.png",
  "花痴": "ac38.png",
  "茶": "ac39.png",
  "衰": "ac40.png",
  "计划通": "ac41.png",
  "赞同": "ac42.png",
  "闪光": "ac43.png",
  "黑枪": "ac44.png",
};

const a2Smiles: Record<string, string> = {
  goodjob: "a2_02.png",
  "偷笑": "a2_03.png",
  "怒": "a2_04.png",
  "诶嘿": "a2_05.png",
  "笑": "a2_07.png",
  "那个…": "a2_08.png",
  "那个...": "a2_08.png",
  "哦嗬嗬嗬": "a2_09.png",
  "舔": "a2_10.png",
  "有何贵干": "a2_11.png",
  "病娇": "a2_12.png",
  lucky: "a2_13.png",
  "鬼脸": "a2_14.png",
  "大哭": "a2_15.png",
  "冷": "a2_16.png",
  "哭": "a2_17.png",
  "妮可妮可妮": "a2_18.png",
  "惊": "a2_19.png",
  poi: "a2_20.png",
  "恨": "a2_21.png",
  "囧2": "a2_22.png",
  "中枪": "a2_23.png",
  "囧": "a2_24.png",
  "你看看你": "a2_25.png",
  yes: "a2_26.png",
  doge: "a2_27.png",
  "自戳双目": "a2_28.png",
  "偷吃": "a2_30.png",
  "冷笑": "a2_31.png",
  "壁咚": "a2_32.png",
  "不活了": "a2_33.png",
  "不明觉厉": "a2_36.png",
  "jojo立": "a2_37.png",
  "jojo立2": "a2_38.png",
  "jojo立3": "a2_39.png",
  "jojo立5": "a2_40.png",
  "jojo立4": "a2_41.png",
  "威吓": "a2_42.png",
  "你已经死了": "a2_45.png",
  "异议": "a2_47.png",
  "认真": "a2_48.png",
  "你这种人…": "a2_49.png",
  "你这种人...": "a2_49.png",
  "是在下输了": "a2_51.png",
  "抢镜头": "a2_52.png",
  "你为猴这么": "a2_53.png",
  "干杯": "a2_54.png",
  "干杯2": "a2_55.png",
};

const ngSmiles: Record<string, string> = {
  "呲牙笑": "ng_1.png",
  "奸笑": "ng_2.png",
  "问号": "ng_3.png",
  "茶": "ng_4.png",
  "笑指": "ng_5.png",
  "燃尽": "ng_6.png",
  "晕": "ng_7.png",
  "扇笑": "ng_8.png",
  "寄": "ng_9.png",
  "别急": "ng_10.png",
  doge: "ng_11.png",
  "丧": "ng_12.png",
  "汗": "ng_13.png",
  "叹气": "ng_15.png",
  "吃饼": "ng_16.png",
  "吃瓜": "ng_17.png",
  "吐舌": "ng_18.png",
  "哭": "ng_19.png",
  "喘": "ng_20.png",
  "心": "ng_21.png",
  "喷": "ng_22.png",
  "困": "ng_24.png",
  "大哭": "ng_25.png",
  "大惊": "ng_26.png",
  "害怕": "ng_27.png",
  "惊": "ng_28.png",
  "暴怒": "ng_30.png",
  "气愤": "ng_31.png",
  "热": "ng_32.png",
  "瓜不熟": "ng_33.png",
  "瞎": "ng_34.png",
  "色": "ng_35.png",
  "斜眼": "ng_37.png",
  "问号大": "ng_38.png",
};

const smileGroups: Record<string, Record<string, string>> = {
  "0": defaultSmiles,
  ac: acSmiles,
  a2: a2Smiles,
  ng: ngSmiles,
};

export const ngaSmileGroups = [
  {
    key: "ac",
    label: "AC娘",
    smiles: Object.entries(acSmiles).map(([name, fileName]) => ({
      name,
      code: `[s:ac:${name}]`,
      url: `${NGA_SMILE_BASE_URL}${fileName}`,
    })),
  },
  {
    key: "a2",
    label: "AC娘2",
    smiles: Object.entries(a2Smiles).map(([name, fileName]) => ({
      name,
      code: `[s:a2:${name}]`,
      url: `${NGA_SMILE_BASE_URL}${fileName}`,
    })),
  },
  {
    key: "ng",
    label: "NG",
    smiles: Object.entries(ngSmiles).map(([name, fileName]) => ({
      name,
      code: `[s:ng:${name}]`,
      url: `${NGA_SMILE_BASE_URL}${fileName}`,
    })),
  },
] as const;

export type NgaSmileGroupKey = typeof ngaSmileGroups[number]["key"];

export function resolveNgaSmileUrl(group: string, name: string) {
  const normalizedGroup = group.trim().toLowerCase();
  const normalizedName = name.trim();
  const fileName = smileGroups[normalizedGroup]?.[normalizedName];
  return fileName ? `${NGA_SMILE_BASE_URL}${fileName}` : null;
}

export const acEmoticons: Record<string, string> = Object.fromEntries(
  Object.entries({ ...acSmiles, ...a2Smiles }).map(([name, fileName]) => [name, `${NGA_SMILE_BASE_URL}${fileName}`])
);
